"""统一错误码定义."""

from enum import Enum


class ErrorCode(str, Enum):
    """OpenBase 统一错误码.

    分段规则：AUTH_* 鉴权授权 / PARAM_* 参数 / BIZ_* 业务 / SYS_* 系统 / STORAGE_* 存储。
    """

    # ---- 成功 ----
    OK = "0"

    # ---- 鉴权/授权 ----
    AUTH_UNAUTHORIZED = "AUTH_401"
    AUTH_FORBIDDEN = "AUTH_403"
    AUTH_TOKEN_EXPIRED = "AUTH_401_EXPIRED"
    AUTH_TOKEN_INVALID = "AUTH_401_INVALID"
    AUTH_RATE_LIMITED = "AUTH_429"
    AUTH_USER_DISABLED = "AUTH_401_DISABLED"

    # ---- 参数 ----
    PARAM_VALIDATION_ERROR = "PARAM_422"
    PARAM_NOT_FOUND = "PARAM_404"
    PARAM_INVALID = "PARAM_INVALID"
    PARAM_AGGREGATE_STEP_INVALID = "PARAM_AGGREGATE_STEP_INVALID"

    # ---- 业务 ----
    BIZ_TENANT_EXISTS = "BIZ_TENANT_EXISTS"
    BIZ_TENANT_NOT_FOUND = "BIZ_TENANT_NOT_FOUND"
    BIZ_USER_EXISTS = "BIZ_USER_EXISTS"
    BIZ_ROLE_IN_USE = "BIZ_ROLE_IN_USE"
    BIZ_CONFIG_CONFLICT = "BIZ_CONFIG_CONFLICT"
    BIZ_NOT_FOUND = "BIZ_404"
    BIZ_CONFLICT = "BIZ_CONFLICT"
    BIZ_MODEL_QUOTA = "BIZ_MODEL_QUOTA"
    BIZ_AGGREGATE_PARTIAL_FAILURE = "BIZ_AGGREGATE_PARTIAL_FAILURE"

    # ---- 权限（PERM_ 前缀，四维管理域） ----
    PERM_FORBIDDEN = "PERM_FORBIDDEN"

    # ---- P2-1 协议头/信任链（设计草案 §3.8 错误码表） ----
    # 非受信来源携带身份头（V-5 定案/D-V5）：门禁后入口校验 / 下游 K02 落地
    PERM_UNTRUSTED_IDENTITY_HEADER = "PERM_UNTRUSTED_IDENTITY_HEADER"
    # 委托请求 + DB 不可达/行缺失无法证明不变式（V-2/V-3 fail-closed）
    PERM_DELEGATION_VERIFY_UNAVAILABLE = "PERM_DELEGATION_VERIFY_UNAVAILABLE"
    # 规范头格式/类型非法（validate_identity_headers）
    PARAM_HEADER_FORMAT_INVALID = "PARAM_HEADER_FORMAT_INVALID"
    # 未绑定服务账号的 ob_k_/X-API-Key 匿名业务写被拒（D-V6，K03 收口后）
    PERM_SERVICE_KEY_WRITE_DENIED = "PERM_SERVICE_KEY_WRITE_DENIED"
    # X-Org-ID ≠ X-Tenant-ID 别名（§7.1 强模式，开关化；批次 2/T7 接线）
    BIZ_ORG_ALIAS_MISMATCH = "BIZ_ORG_ALIAS_MISMATCH"

    # ---- 存储 ----
    STORAGE_FILE_NOT_FOUND = "STORAGE_404"

    # ---- 系统 ----
    SYS_INTERNAL_ERROR = "SYS_500"
    SYS_UPSTREAM_ERROR = "SYS_502"
    SYS_TIMEOUT = "SYS_TIMEOUT"

    # ---- 网关权限（PERM_ 前缀，统一网关域） ----
    PERM_GATEWAY_REGISTER = "PERM_GATEWAY_REGISTER"
    PERM_GATEWAY_AGGREGATE = "PERM_GATEWAY_AGGREGATE"
    PERM_GATEWAY_VIEW = "PERM_GATEWAY_VIEW"

    # ---- v1.4.1 服务 Key 认证 ----
    AUTH_API_KEY_INVALID = "AUTH_API_KEY_INVALID"
    PERM_API_KEY_SCOPE = "PERM_API_KEY_SCOPE"

    # ---- U1 统一身份收口（设计草案 §10.3，RA-01/OB-1 起逐步启用） ----
    AUTH_PRINCIPAL_DISABLED = "AUTH_PRINCIPAL_DISABLED"
    AUTH_TOKEN_STALE = "AUTH_TOKEN_STALE"
    BIZ_STATE_TRANSITION_INVALID = "BIZ_STATE_TRANSITION_INVALID"
    PERM_DELEGATION_CROSS_TENANT = "PERM_DELEGATION_CROSS_TENANT"
    PERM_DELEGATION_ROLE = "PERM_DELEGATION_ROLE"
    BIZ_PURGE_AUTH_REQUIRED = "BIZ_PURGE_AUTH_REQUIRED"
    BIZ_NOT_PURGEABLE = "BIZ_NOT_PURGEABLE"


# HTTP 状态码映射
ERROR_HTTP_MAP: dict[ErrorCode, int] = {
    ErrorCode.AUTH_UNAUTHORIZED: 401,
    ErrorCode.AUTH_FORBIDDEN: 403,
    ErrorCode.AUTH_TOKEN_EXPIRED: 401,
    ErrorCode.AUTH_TOKEN_INVALID: 401,
    ErrorCode.AUTH_RATE_LIMITED: 429,
    ErrorCode.AUTH_USER_DISABLED: 401,
    ErrorCode.PARAM_VALIDATION_ERROR: 422,
    ErrorCode.PARAM_NOT_FOUND: 404,
    ErrorCode.PARAM_INVALID: 400,
    ErrorCode.PARAM_AGGREGATE_STEP_INVALID: 400,
    ErrorCode.BIZ_TENANT_EXISTS: 409,
    ErrorCode.BIZ_TENANT_NOT_FOUND: 404,
    ErrorCode.BIZ_USER_EXISTS: 409,
    ErrorCode.BIZ_ROLE_IN_USE: 409,
    ErrorCode.BIZ_CONFIG_CONFLICT: 409,
    ErrorCode.BIZ_NOT_FOUND: 404,
    ErrorCode.BIZ_CONFLICT: 409,
    ErrorCode.BIZ_MODEL_QUOTA: 402,
    ErrorCode.BIZ_AGGREGATE_PARTIAL_FAILURE: 200,
    ErrorCode.PERM_FORBIDDEN: 403,
    # P2-1 协议头/信任链
    ErrorCode.PERM_UNTRUSTED_IDENTITY_HEADER: 403,
    ErrorCode.PERM_DELEGATION_VERIFY_UNAVAILABLE: 403,
    ErrorCode.PARAM_HEADER_FORMAT_INVALID: 400,
    ErrorCode.PERM_SERVICE_KEY_WRITE_DENIED: 403,
    ErrorCode.BIZ_ORG_ALIAS_MISMATCH: 403,
    ErrorCode.STORAGE_FILE_NOT_FOUND: 404,
    ErrorCode.SYS_INTERNAL_ERROR: 500,
    ErrorCode.SYS_UPSTREAM_ERROR: 502,
    ErrorCode.SYS_TIMEOUT: 503,
    ErrorCode.PERM_GATEWAY_REGISTER: 403,
    ErrorCode.PERM_GATEWAY_AGGREGATE: 403,
    ErrorCode.PERM_GATEWAY_VIEW: 403,
    ErrorCode.AUTH_API_KEY_INVALID: 401,
    ErrorCode.PERM_API_KEY_SCOPE: 403,
    # U1 统一身份收口（§10.3）
    ErrorCode.AUTH_PRINCIPAL_DISABLED: 401,
    ErrorCode.AUTH_TOKEN_STALE: 401,
    ErrorCode.BIZ_STATE_TRANSITION_INVALID: 400,
    ErrorCode.PERM_DELEGATION_CROSS_TENANT: 403,
    ErrorCode.PERM_DELEGATION_ROLE: 403,
    ErrorCode.BIZ_PURGE_AUTH_REQUIRED: 403,
    ErrorCode.BIZ_NOT_PURGEABLE: 400,
}
